### ISSUE TITLE
Initial data load queue creation fix

### ISSUE THREAD

**Issue by srezacova** [openkfw/Oscar#78]
**Describe the bug**
When you add name of the queue to NEW_STORAGE_QUEUES in ./.env file, storage queue should be created in Azure storage Queues folder. This is not working.

**To Reproduce**
1. In main branch set in ./.env  NEW_STORAGE_QUEUES=new-queue-test
2. Run ./start.sh, ./runinitialload.sh
3. Check logs from initial-data-load, there are these logs:
initial-data-load-service_1  | 2021-10-14T12:35:55.352Z [oscar-initial-data-upload] info: Creating storage queue: new-queue-test
initial-data-load-service_1  | 2021-10-14T12:35:55.458Z [oscar-initial-data-upload] info: Storage queue new-queue-test already exists.
initial-data-load-service_1  | RestError: Server failed to authenticate the request.Make sure the value of the Authorization header is formed correctly including the signature.
initial-data-load-service_1  | RequestId:0d19c1c2-13ce-417f-baa7-a1c4e4a7d57c
initial-data-load-service_1  | Time:2021-10-14T12:35:55.440Z
4.There is nothing in Queues folder in Azure Storage Explorer

**Aditional context**
-When error occurs in createStorageQueue function, there is message in the log:
`Storage queue ${queueName} already exists.\n${err}`
We need the text to be more general, because in this case it is not true and it is misleading.
-This functionality work in our second repo in master, so thats weird.

**Comment by LeonPlumpe** [comment]
Cannot replicate issue:
- added in ./.env NEW_STORAGE_QUEUES=new-queue-test
- started the app (./start.sh)
- ran ./runinitialload.sh

logs of initialload:
initial-data-load-service_1  | 2021-12-09T11:27:56.692Z [oscar-initial-data-upload] info: raw-data container was created.
initial-data-load-service_1  | 2021-12-09T11:27:56.693Z [oscar-initial-data-upload] info: Creating storage queue: new-queue-test
initial-data-load-service_1  | 2021-12-09T11:27:56.763Z [oscar-initial-data-upload] info: Uploading geo data for map layers...

**Comment by srezacova** [comment]
> Cannot replicate issue:
> 
> * added in ./.env NEW_STORAGE_QUEUES=new-queue-test
> * started the app (./start.sh)
> * ran ./runinitialload.sh
> 
> logs of initialload: initial-data-load-service_1 | 2021-12-09T11:27:56.692Z [oscar-initial-data-upload] info: raw-data container was created. initial-data-load-service_1 | 2021-12-09T11:27:56.693Z [oscar-initial-data-upload] info: Creating storage queue: new-queue-test initial-data-load-service_1 | 2021-12-09T11:27:56.763Z [oscar-initial-data-upload] info: Uploading geo data for map layers...

Seems to work for me now as well, I will ask Daniela but probably we can close this.
