### ISSUE TITLE
Get gpkg file, save it to db and show on FE

### ISSUE THREAD

**Issue by srezacova** [openkfw/Oscar#82]
Till now we just processed geojson files, now we want also gpkg files.

- [x] Load .gpkg files from folder in data as we do with .geojson
- [x] add gpkg as format option for geoData
- [x] Store the file in azure storage and new document in database
- [x] Create test mapLayer for this data
- [x] Check, if file is correctly fetched in ui
- [ ] show the .gpkg in openlayers, (maybe inspire by https://github.com/ahocevar/openlayers-geopackage-demo/blob/master/src/geopackage.js)

**Dependencies**
https://github.com/openkfw/Oscar/pull/81

**Definition of done**
.gpkg file in data in initial-load is loaded and displayed in ui

**Comment by bariela** [comment]
There is no suitable npm library for handling .gpkg files in production frontend.
